type SubjectArea =
    "economyAndFinance"
    | "workAndSocialAffairs"
    | "educationAndResearch"
    | "healthAndCare"
    | "familyAndSociety"
    | "environmentAndClimate"
    | "migrationAndIntegration"
    | "foreignPolicy"
    | "securityAndDefense"
    | "transportationAndInfrastructure"
    | "digitalizationAndTechnology"
    | "europe"
    | "democracyAndRuleOfLaw"
    | "innovationAndFuture"
export type Suggestion = {
    questionType: "general" | "specific" | "search"
    parties: string[]
    category: SubjectArea
    question: string
}

export const suggestions: Suggestion[] = [
    // Wirtschaft & Finanzen
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Wie wollen die Parteien die Wirtschaft aus der Rezession führen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Maßnahmen sind zur Senkung der Unternehmenssteuern geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Wie soll die Inflation unter Kontrolle gebracht werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Strategien gibt es zur Förderung von Start-ups?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Wie stehen die Parteien zur Einführung einer Vermögenssteuer?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Was planen die Parteien zur Bekämpfung der Staatsverschuldung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Pläne gibt es zur Förderung des Mittelstands?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Wie soll die Wettbewerbsfähigkeit Deutschlands gestärkt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Maßnahmen sind zur Förderung von Investitionen geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Wie wollen die Parteien die Digitalisierung der Wirtschaft vorantreiben?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "economyAndFinance",
        "question": "Was planen CDU/CSU und FDP zur Senkung der Einkommenssteuer?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "economyAndFinance",
        "question": "Wie stehen SPD und CDU/CSU zur Einführung einer Finanztransaktionssteuer?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "economyAndFinance",
        "question": "Wie stehen Grüne und CDU/CSU zur Erhöhung der Abgaben auf Kapitalerträge?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "economyAndFinance",
        "question": "Welche Positionen vertreten AfD und Linke zur Abschaffung des Solidaritätszuschlags?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "bsw"],
        "category": "economyAndFinance",
        "question": "Was planen Grüne und BSW zur Förderung nachhaltiger Wirtschaftspraktiken?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "economyAndFinance",
        "question": "Wie wollen CDU/CSU und SPD die Exportwirtschaft stärken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien fordern die Einführung eines bedingungslosen Grundeinkommens?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien setzen sich für die Abschaffung der Erbschaftssteuer ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien planen eine Reform der Mehrwertsteuer?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien wollen die Schuldenbremse lockern?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien fordern eine Finanztransaktionssteuer?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "economyAndFinance",
        "question": "Welche Parteien planen höhere Abgaben auf Kapitalerträge?",
    },

    // Arbeit & Soziales
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Wie wollen die Parteien den Fachkräftemangel bekämpfen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Maßnahmen sind zur Sicherung der Renten geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Wie soll die Zahl der Bürgergeldempfänger gesenkt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Pläne gibt es zur Förderung von Weiterbildungen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Wie stehen die Parteien zur Erhöhung des Mindestlohns?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Was wird gegen die Zunahme von Teilzeitarbeit unternommen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Wie soll die Vereinbarkeit von Beruf und Familie verbessert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Strategien gibt es zur Bekämpfung der Altersarmut?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Wie wollen die Parteien die Integration von Migranten in den Arbeitsmarkt fördern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Was planen die Parteien zur Unterstützung von Alleinerziehenden?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "cdu-csu"],
        "category": "workAndSocialAffairs",
        "question": "Was planen SPD und CDU/CSU zur Reform des Bürgergelds?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "workAndSocialAffairs",
        "question": "Wie stehen Grüne und FDP zur Einführung einer Vier-Tage-Woche?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "workAndSocialAffairs",
        "question": "Welche Positionen vertreten AfD und Linke zur Verlängerung der Lebensarbeitszeit?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "gruene"],
        "category": "workAndSocialAffairs",
        "question": "Was planen CDU/CSU und Grüne zur Bekämpfung der Kinderarmut?",
    },
    {
        "questionType": "specific",
        "parties": ["fdp", "spd"],
        "category": "workAndSocialAffairs",
        "question": "Wie wollen FDP und SPD die Digitalisierung der Arbeitswelt gestalten?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien fordern eine Erhöhung des Renteneintrittsalters?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien setzen sich für ein bedingungsloses Grundeinkommen ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien planen Maßnahmen gegen befristete Arbeitsverträge?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien wollen die Sozialabgaben für Geringverdiener senken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien streben eine Reform der Arbeitslosenversicherung an?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "workAndSocialAffairs",
        "question": "Welche Parteien planen eine Flexibilisierung der Arbeitszeiten?",
    },

    // Bildung & Forschung
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Wie wollen die Parteien die Digitalisierung in Schulen vorantreiben?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Maßnahmen sind zur Bekämpfung des Lehrermangels geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Wie soll die Chancengleichheit im Bildungssystem verbessert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Pläne gibt es zur Unterstützung von Kindern mit Förderstatus?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Wie stehen die Parteien zur Einführung von Ganztagsschulen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Was wird gegen den Sanierungsstau an Schulen unternommen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Strategien gibt es zur Verbesserung der frühkindlichen Bildung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Wie soll die berufliche Bildung attraktiver gestaltet werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Maßnahmen sind zur Förderung der Inklusion im Bildungssystem geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Wie wollen die Parteien den Übergang von Schule zu Beruf verbessern?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "educationAndResearch",
        "question": "Was planen SPD und Grüne zur Reform des BAföG?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "educationAndResearch",
        "question": "Wie stehen CDU/CSU und FDP zur Einführung von Bildungsstandards?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "educationAndResearch",
        "question": "Welche Positionen vertreten AfD und Linke zur Abschaffung von Studiengebühren?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "bsw"],
        "category": "educationAndResearch",
        "question": "Was planen Grüne und BSW zur Förderung der Klimabildung in Schulen?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "educationAndResearch",
        "question": "Wie wollen CDU/CSU und SPD die Hochschulfinanzierung sichern?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Parteien fordern die Einführung eines Pflichtfachs Informatik?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Parteien setzen sich für kleinere Klassenstärken ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Parteien planen eine Reform der Lehrerbildung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Parteien wollen mehr Mittel für die Geisteswissenschaften bereitstellen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "educationAndResearch",
        "question": "Welche Parteien streben eine Stärkung der dualen Ausbildung an?",
    },

    // Gesundheit & Pflege
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Wie wollen die Parteien den Ärztemangel bekämpfen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Maßnahmen sind zur Verbesserung der Pflegequalität geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Wie soll die Finanzierung der Pflegeversicherung gesichert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Strategien gibt es zur Förderung der Telemedizin?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Wie stehen die Parteien zur Einführung einer Bürgerversicherung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Wie stehen die Parteien zur Einführung der elektronischen Patientenakte?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Was wird gegen die Schließung von Pflegeeinrichtungen unternommen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Pläne gibt es zur Entlastung pflegender Angehöriger?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "healthAndCare",
        "question": "Wie soll die psychische Gesundheitsversorgung verbessert werden?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "healthAndCare",
        "question": "Was planen SPD und Grüne zur Reform der Pflegeversicherung?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "healthAndCare",
        "question": "Wie stehen CDU/CSU und FDP zur Einführung von Pflegevollversicherungen?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "healthAndCare",
        "question": "Welche Positionen vertreten AfD und Linke zur Abschaffung der privaten Krankenversicherung?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "bsw"],
        "category": "healthAndCare",
        "question": "Was planen Grüne und BSW zur Förderung alternativer Heilmethoden?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "healthAndCare",
        "question": "Wie wollen CDU/CSU und SPD die Krankenhausfinanzierung sichern?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Parteien fordern die Einführung einer Pflegevollversicherung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Parteien setzen sich für höhere Löhne in der Pflege ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Parteien planen eine Reform der Notfallversorgung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Parteien wollen die Beitragsbemessungsgrenze in der Krankenversicherung anheben?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "healthAndCare",
        "question": "Welche Parteien möchten den Eigenanteil an den Pflegeheimkosten senken?",
    },

    // Familie & Gesellschaft
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Wie wollen die Parteien die Vereinbarkeit von Beruf und Familie verbessern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Maßnahmen sind zur Förderung der Geburtenrate geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Wie soll die finanzielle Unterstützung für Familien erhöht werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Strategien gibt es zur Bekämpfung der Kinderarmut?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Was wird gegen den Mangel an Kitaplätzen unternommen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Pläne gibt es zur Unterstützung von Alleinerziehenden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Wie soll die Integration von Migrantenfamilien gefördert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Maßnahmen sind zur Stärkung des Ehrenamts geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Wie wollen die Parteien den gesellschaftlichen Zusammenhalt fördern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Wie wollen die Parteien die Schere zwischen Arm und Reich verkleinern?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "familyAndSociety",
        "question": "Was planen SPD und Grüne zur Erhöhung des Elterngelds?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "familyAndSociety",
        "question": "Wie stehen CDU/CSU und FDP zur Einführung eines Familiensplittings?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "familyAndSociety",
        "question": "Welche Positionen vertreten AfD und Linke zur Abschaffung des Ehegattensplittings?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "familyAndSociety",
        "question": "Wie wollen CDU/CSU und SPD die Kinderbetreuung ausbauen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Parteien fordern die Einführung einer Kindergrundsicherung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Parteien planen eine Reform des Familienrechts?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Parteien wollen die finanzielle Unterstützung für pflegende Angehörige erhöhen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "familyAndSociety",
        "question": "Welche Parteien streben eine Stärkung der Rechte gleichgeschlechtlicher Partnerschaften an?",
    },

    // Umwelt & Klima
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie wollen die Parteien die Klimaziele für 2030 erreichen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Maßnahmen sind zum Schutz der Biodiversität geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie soll der Ausbau erneuerbarer Energien beschleunigt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie stehen die Parteien zum Ausbau erneuerbarer Energien?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie möchten die Parteien Speichertechnologien für erneuerbare Energien voranbringen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Maßnahmen sind zur Reduzierung des CO₂-Ausstoßes geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie stehen die Parteien zur Einführung einer CO₂-Steuer?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie stehen die Parteien zur Wiederaufnahme des Betriebs existierender Kernkraftwerke?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie stehen die Parteien zum Bau neuer Kernkraftwerke?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie stehen die Parteien zur Kernfusion als Energiequelle?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Maßnahmen sind zur Reduzierung des CO₂-Ausstoßes im Verkehrssektor geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Pläne gibt es zur Förderung nachhaltiger Landwirtschaft?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie soll der Flächenverbrauch für Siedlungen und Verkehr reduziert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Maßnahmen sind zur Verbesserung der Luftqualität geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Wie wollen die Parteien den Waldschutz stärken?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Maßnahmen sind zur Verbesserung des Klimas in Großstädten geplant?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "spd"],
        "category": "environmentAndClimate",
        "question": "Was planen Grüne und SPD zur Förderung von E-Mobilität?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "environmentAndClimate",
        "question": "Wie stehen CDU/CSU und FDP zur Verlängerung der Atomkraftnutzung?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "environmentAndClimate",
        "question": "Welche Positionen vertreten AfD und Linke zur Kohleverstromung?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "bsw"],
        "category": "environmentAndClimate",
        "question": "Was planen Grüne und BSW zur Förderung von Klimaschutzprojekten?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "environmentAndClimate",
        "question": "Wie wollen CDU/CSU und SPD den Emissionshandel reformieren?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien fordern ein Tempolimit auf Autobahnen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien setzen sich für ein Verbot von Einwegplastik ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien planen strengere Vorgaben für den CO₂-Ausstoß?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien wollen den Ausbau der Windenergie vorantreiben?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien streben ein Verbot von Verbrennungsmotoren an?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien leugnen den menschengemachten Klimawandel?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien möchten existierende Kernkraftwerke wieder in Betrieb nehmen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien fordern den Neubau von Kernkraftwerken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien fordern die Nutzung von Kernfusion zur Energiegewinnung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "environmentAndClimate",
        "question": "Welche Parteien haben konkrete Pläne zu Speichertechnologien für erneuerbare Energien?",
    },

    // Migration & Integration
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Wie stehen die Parteien zu Rückweisungen an der Grenze?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Position haben die Parteien zur Rückweisung bei Straftaten?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Wie stehen die Parteien zur Abschiebung syrischer Flüchtlinge nach dem Sturz des Assad-Regimes?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Maßnahmen sind zur Reduzierung islamistisch motivierter Straftaten geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Maßnahmen sind zur verlässlichen Rückführung von Migranten ohne Bleiberecht geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Maßnahmen sind zur Reduzierung des Flüchtlingsaufkommens geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Wie Stehen die Parteien zum Bürgergeld für Ukraineflüchtlinge?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "migrationAndIntegration",
        "question": "Was planen CDU/CSU und SPD zu Grenzrückweisungen?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "linke"],
        "category": "migrationAndIntegration",
        "question": "Wie stehen Grüne und Linke zur Rückweisung bei Straftaten?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "fdp"],
        "category": "migrationAndIntegration",
        "question": "Was fordern Grüne und CDU/CSU zum Umgang mit syrischen Flüchtlingen?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "migrationAndIntegration",
        "question": "Welche Pläne haben CDU/CSU und Grüne für Ukraineflüchtlinge?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien unterstützen Grenzrückweisungen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien lehnen Rückweisungen bei Straftaten ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien fordern die Abschiebung syrischer Flüchtlinge?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien wollen Sozialhilfe für Ukraineflüchtlinge kürzen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Wie wollen die Parteien illegale Migration verhindern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Maßnahmen planen die Parteien zur Integration von Flüchtlingen?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "afd"],
        "category": "migrationAndIntegration",
        "question": "Was fordern CDU/CSU und AfD zur Abschiebung straffälliger Migranten?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "linke"],
        "category": "migrationAndIntegration",
        "question": "Wie stehen Grüne und Linke zur Aufnahme weiterer Flüchtlinge?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien setzen sich für Familiennachzug von Flüchtlingen ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Parteien wollen Asylverfahren beschleunigen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Wie positionieren sich die Parteien zur EU-Asylpolitik?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "migrationAndIntegration",
        "question": "Welche Haltung haben die Parteien zur Seenotrettung im Mittelmeer?",
    },

    // Außenpolitik
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Wie soll die deutsche Außenpolitik auf Trumps Wiederwahl reagieren?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Maßnahmen sind zur Unterstützung Israels geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Maßnahmen sind zum Umgang mit den von Trump angekündigten Zöllen geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Wie stehen die Parteien zur weiteren Waffenlieferungen an die Ukraine?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Rolle spielt Deutschland im Nahost-Friedensprozess?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Wie soll die Zusammenarbeit mit den USA unter Trump gestaltet werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Strategien gibt es zur Stabilisierung des Nahen Ostens?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Wie wird die deutsche Sicherheitspolitik neu ausgerichtet?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Position vertritt Deutschland zu Waffenlieferungen an die Ukraine?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Wie soll die humanitäre Hilfe für Gaza verstärkt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Maßnahmen sind zur Eindämmung russischer Aggressionen geplant?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "foreignPolicy",
        "question": "Was planen CDU/CSU und SPD zur Unterstützung der Ukraine?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "foreignPolicy",
        "question": "Wie stehen Grüne und FDP zur deutschen Israel-Politik?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "foreignPolicy",
        "question": "Welche Haltung haben AfD und Linke zum Ukraine-Konflikt?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "foreignPolicy",
        "question": "Wie positionieren sich SPD und Grüne zur US-Außenpolitik unter Trump?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "foreignPolicy",
        "question": "Welche Pläne haben CDU/CSU und FDP für den Nahost-Friedensprozess?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "foreignPolicy",
        "question": "Wie stehen CDU/CSU und AfD zur Wiederaufnahme von Gaslieferungen aus Russland?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "foreignPolicy",
        "question": "Wie stehen Linke und BSW zur Wiederaufnahme von Gaslieferungen aus Russland?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien fordern eine stärkere Unterstützung für die Ukraine?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien lehnen Waffenlieferungen an Israel ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien befürworten eine enge Zusammenarbeit mit den USA?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien setzen sich für eine diplomatische Lösung im Ukraine-Konflikt ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien unterstützen humanitäre Hilfen für den Gaza-Streifen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "foreignPolicy",
        "question": "Welche Parteien möchten die Gaslieferungen aus Russland wieder aufnehmen?",
    },

    // Sicherheit & Verteidigung
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie soll die Bundeswehr modernisiert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie viel Prozent des Bruttoinlandproduktes möchten die Parteien für Verteidigung investieren?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie wird die NATO-Partnerschaft gestärkt?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Pläne gibt es für den Zivilschutz?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie soll der Terrorismus bekämpft werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Maßnahmen zur Modernisierung der Bundeswehr geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie stehen die Parteien zur Vorratsdatenspeicherung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie stehen die Parteien zur Stationierung amerikanischer Mittelstreckenraketen in Deutschland?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Wie wird die Resilienz kritischer Infrastrukturen erhöht?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Maßnahmen sind zur Bekämpfung von Extremismus geplant?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "securityAndDefense",
        "question": "Was planen CDU/CSU und SPD zur Erhöhung des Verteidigungsetats?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "linke"],
        "category": "securityAndDefense",
        "question": "Wie stehen Grüne und Linke zu Auslandseinsätzen der Bundeswehr?",
    },
    {
        "questionType": "specific",
        "parties": ["fdp", "afd"],
        "category": "securityAndDefense",
        "question": "Welche Positionen vertreten FDP und AfD zur Wiedereinführung der Wehrpflicht?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "securityAndDefense",
        "question": "Wie stehen CDU/CSU und Grüne zur Vorratsdatenspeicherung?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "securityAndDefense",
        "question": "Wie wollen CDU/CSU und FDP die Polizei unterstützen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Parteien fordern den Abzug der US-Truppen aus Deutschland?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Parteien lehnen Rüstungsexporte ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Parteien setzen sich für eine europäische Armee ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Parteien befürworten die Anschaffung bewaffneter Drohnen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "securityAndDefense",
        "question": "Welche Parteien sind gegen die Erhöhung des Verteidigungsbudgets?",
    },

    // Verkehr & Infrastruktur
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie soll die Verkehrsinfrastruktur modernisiert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Pläne gibt es für den Ausbau des Schienennetzes?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie soll die Bahninfrastruktur modernisiert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie wird die Sanierung maroder Brücken vorangetrieben?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Maßnahmen sind für den Radwegebau vorgesehen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie soll der öffentliche Nahverkehr verbessert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie stehen die Parteien zum Einsatz von E-Fuels im Individualverkehr?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Strategien gibt es gegen Verkehrsstau in Städten?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie stehen die Parteien zum Deutschlandticket?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie stehen die Parteien zum Ausbau der Autobahnen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie wird die Elektromobilität gefördert?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Pläne gibt es für den Ausbau von Ladesäulen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Wie soll der Güterverkehr umweltfreundlicher gestaltet werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Investitionen sind in den ÖPNV geplant?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "transportationAndInfrastructure",
        "question": "Was planen CDU/CSU und SPD zur Autobahnsanierung?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "transportationAndInfrastructure",
        "question": "Welche Position haben Grüne und FDP zum Tempolimit?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "transportationAndInfrastructure",
        "question": "Was fordern AfD und Linke beim Ausbau des Straßennetzes?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "transportationAndInfrastructure",
        "question": "Welche Maßnahmen planen SPD und Grüne für den Radverkehr?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "transportationAndInfrastructure",
        "question": "Wie stehen CDU/CSU und FDP zur Förderung von E-Autos?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien unterstützen ein generelles Tempolimit?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien setzen sich für kostenlosen ÖPNV ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien lehnen den Ausbau von Autobahnen ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien fordern mehr Investitionen in die Bahn?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien planen die Förderung von Wasserstoffantrieben?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien fordern den Einsatz von E-Fuels im Individualverkehr?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "transportationAndInfrastructure",
        "question": "Welche Parteien fordern ein Verbot von Verbrennermotoren?",
    },

    // Digitalisierung & Technologie
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie wollen die Parteien die digitale Infrastruktur verbessern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Mindestgeschwindigkeit möchte die Parteien für Internetanschlüsse gesetzlich regeln?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie soll eine flächendeckende Breitbandversorgung realisiert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie möchten die Parteien wichtige Industriezweige in Deutschland ansiedeln und halten?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Maßnahmen sind zur Förderung von Start-ups geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie soll die Cybersicherheit in Deutschland gestärkt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Pläne gibt es für den Ausbau von E-Government-Diensten?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie stehen die Parteien zur Regulierung von Künstlicher Intelligenz?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Strategien gibt es gegen den Fachkräftemangel in der IT-Branche?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie soll die Digitalisierung im Bildungswesen vorangetrieben werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Maßnahmen sind zur Förderung der digitalen Teilhabe geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie stehen die Parteien zum Datenschutz?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Pläne gibt es für den Einsatz von Open-Source-Software?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie stehen die Parteien zur Förderung der Herstellung von Batteriezellen in Deutschland?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Wie möchten die Parteien flächendeckenden Mobilfunkempfang sicherstellen?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "digitalizationAndTechnology",
        "question": "Was planen CDU/CSU und SPD zur Förderung von KI-Technologien?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "digitalizationAndTechnology",
        "question": "Wie wollen Grüne und FDP den Breitbandausbau beschleunigen?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "digitalizationAndTechnology",
        "question": "Welche Positionen vertreten AfD und Linke zur Netzneutralität?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "digitalizationAndTechnology",
        "question": "Was planen SPD und Grüne zur Digitalisierung der Verwaltung?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "digitalizationAndTechnology",
        "question": "Wie stehen CDU/CSU und AfD zur Digitalisierung der Verwaltung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien fordern ein Digitalministerium?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien setzen sich für ein Recht auf Homeoffice ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien planen Investitionen in digitale Bildung?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien lehnen die Vorratsdatenspeicherung ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien unterstützen den Ausbau von 5G-Netzen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "digitalizationAndTechnology",
        "question": "Welche Parteien fordern eine Erhöhung der gesetzlich zugesicherten Mindestbandbreite für Internetanschlüsse?",
    },

    // Europa
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Wie positionieren sich die Parteien zur Aufnahme der Ukraine in die EU?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Welche Pläne gibt es für die Zukunft der Eurozone?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Wie stehen die Parteien zur europäischen Verteidigungspolitik?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Welche Reformen der EU-Institutionen werden vorgeschlagen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Wie soll die EU-Außengrenze besser geschützt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Welche Maßnahmen sind zur Stärkung der EU-Wirtschaft geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Wie soll die EU-Digitalstrategie vorangetrieben werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Welche Positionen gibt es zur europäischen Klimapolitik?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Wie soll die EU-Außenpolitik gestaltet werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "europe",
        "question": "Welche Ansätze gibt es zur Bekämpfung von Steuerflucht in der EU?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "europe",
        "question": "Was planen CDU/CSU und SPD zur EU-Erweiterung?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "europe",
        "question": "Wie stehen Grüne und FDP zur europäischen Verteidigungspolitik?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "europe",
        "question": "Welche EU-Reformen fordern AfD und Die Linke?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "europe",
        "question": "Was planen SPD und Grüne zur EU-Klimapolitik?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "europe",
        "question": "Wie wollen CDU/CSU und FDP die EU-Wirtschaft stärken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien fordern eine stärkere EU-Integration?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien lehnen die EU-Erweiterung ab?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien setzen sich für eine EU-Armee ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien wollen die EU-Kompetenzen reduzieren?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien unterstützen die Einführung von EU-Steuern?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "europe",
        "question": "Welche Parteien möchten aus der EU austreten?",
    },

    // Demokratie & Rechtsstaat
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie wollen die Parteien die Demokratie stärken?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Maßnahmen sind gegen politischen Extremismus geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Maßnahmen sind zur politischen Bildung geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie soll die Unabhängigkeit der Justiz gesichert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Reformen sind für das Wahlrecht vorgesehen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie wird die Transparenz staatlicher Entscheidungen erhöht?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Pläne gibt es zur Bekämpfung von Korruption?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie ist die Position der Parteien zum Wahlrecht ab 16?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie soll die Pressefreiheit geschützt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Schritte sind zur Stärkung der Bürgerrechte geplant?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie wollen die Parteien die politische Bildung fördern?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Maßnahmen sind gegen Hasskriminalität vorgesehen?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "democracyAndRuleOfLaw",
        "question": "Was planen CDU/CSU und SPD zur Reform des Wahlrechts?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie wollen Grüne und FDP die Bürgerrechte stärken?",
    },
    {
        "questionType": "specific",
        "parties": ["linke", "afd"],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Positionen vertreten Linke und AfD zur direkten Demokratie?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "democracyAndRuleOfLaw",
        "question": "Was planen SPD und Grüne gegen politischen Extremismus?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "democracyAndRuleOfLaw",
        "question": "Wie wollen CDU/CSU und FDP die Justiz stärken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien fordern mehr Volksabstimmungen?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien planen Maßnahmen gegen Korruption?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien setzen sich für Pressefreiheit ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien wollen das Wahlrecht reformieren?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien planen Maßnahmen gegen Hasskriminalität?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "democracyAndRuleOfLaw",
        "question": "Welche Parteien fordern ein Wahlrecht ab 16?",
    },

    // Innovation & Zukunft
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Wie fördern die Parteien Start-ups und Innovationen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Pläne gibt es für die Digitalisierung der Verwaltung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Wie soll der Technologiestandort Deutschland gestärkt werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Maßnahmen sind für den Ausbau von KI-Technologien vorgesehen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Wie wollen die Parteien den Fachkräftemangel in Tech-Berufen bekämpfen?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Strategien gibt es für die Förderung von Forschung und Entwicklung?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Wie soll die Zusammenarbeit zwischen Wissenschaft und Wirtschaft verbessert werden?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Pläne gibt es für den Ausbau der digitalen Infrastruktur?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Wie wollen die Parteien den Datenschutz in der digitalen Welt gewährleisten?",
    },
    {
        "questionType": "general",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Maßnahmen sind zur Förderung von E-Government geplant?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "spd"],
        "category": "innovationAndFuture",
        "question": "Was planen CDU/CSU und SPD zur Förderung von Start-ups?",
    },
    {
        "questionType": "specific",
        "parties": ["gruene", "fdp"],
        "category": "innovationAndFuture",
        "question": "Wie stehen Grüne und FDP zur Einführung digitaler Bildungsoffensiven?",
    },
    {
        "questionType": "specific",
        "parties": ["afd", "linke"],
        "category": "innovationAndFuture",
        "question": "Welche Positionen vertreten AfD und Linke zur Nutzung von Künstlicher Intelligenz?",
    },
    {
        "questionType": "specific",
        "parties": ["spd", "gruene"],
        "category": "innovationAndFuture",
        "question": "Was planen SPD und Grüne zur Förderung von Forschung und Entwicklung?",
    },
    {
        "questionType": "specific",
        "parties": ["cdu-csu", "fdp"],
        "category": "innovationAndFuture",
        "question": "Wie wollen CDU/CSU und FDP den Technologiestandort Deutschland stärken?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Parteien setzen sich für die Förderung von Start-ups ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Parteien planen Investitionen in Künstliche Intelligenz?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Parteien fordern den Ausbau der digitalen Infrastruktur?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Parteien setzen sich für die Digitalisierung der Verwaltung ein?",
    },
    {
        "questionType": "search",
        "parties": [],
        "category": "innovationAndFuture",
        "question": "Welche Parteien planen Maßnahmen gegen den Fachkräftemangel in Tech-Berufen?",
    },
]

export const partyAgnosticSuggestions = suggestions.filter(suggestion => suggestion.questionType === "general")
export const partySpecificSuggestions = suggestions.filter(suggestion => suggestion.questionType === "specific")
export const partySearchSuggestions = suggestions.filter(suggestion => suggestion.questionType === "search")